#!/usr/bin/env bun

import solidPlugin from "../node_modules/@opentui/solid/scripts/solid-plugin"
import path from "path"
import fs from "fs"
import { $ } from "bun"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

import pkg from "../package.json"
import { Script } from "@opencode-ai/script"
if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log(`Usage: bun run build [-- <options>]

Default behavior is offline-first (no models.dev fetch).

Options:
  --single            Build only current platform target
  --baseline          Include baseline binary target
  --skip-install      Skip bun install for platform artifacts
  --refresh-models    Refresh models snapshot from models.dev
  -h, --help          Show this help message

Examples:
  bun run build
  bun run build -- --single --skip-install
  bun run build -- --refresh-models
  bun run models:update-snapshot
`)
  process.exit(0)
}

const refreshModels = process.argv.includes("--refresh-models")
const modelsSnapshotPath = path.join(dir, "packages/opencode/src/provider/models-snapshot.ts")
if (process.env.MODELS_DEV_API_JSON || refreshModels) {
  const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
  const modelsData = process.env.MODELS_DEV_API_JSON
    ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
    : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())
  await Bun.write(
    modelsSnapshotPath,
    `// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
  )
  console.log("Generated models-snapshot.ts")
} else {
  console.log("Skipped models snapshot refresh (offline default). Use --refresh-models to update.")
}

const singleFlag = process.argv.includes("--single")
const baselineFlag = process.argv.includes("--baseline")
const skipInstall = process.argv.includes("--skip-install")

const allTargets: {
  os: string
  arch: "arm64" | "x64"
  abi?: "musl"
  avx2?: false
}[] = [
    {
      os: "linux",
      arch: "arm64",
    },
    {
      os: "linux",
      arch: "x64",
    },
    {
      os: "linux",
      arch: "x64",
      avx2: false,
    },
    {
      os: "linux",
      arch: "arm64",
      abi: "musl",
    },
    {
      os: "linux",
      arch: "x64",
      abi: "musl",
    },
    {
      os: "linux",
      arch: "x64",
      abi: "musl",
      avx2: false,
    },
    {
      os: "darwin",
      arch: "arm64",
    },
    {
      os: "darwin",
      arch: "x64",
    },
    {
      os: "darwin",
      arch: "x64",
      avx2: false,
    },
    {
      os: "win32",
      arch: "x64",
    },
    {
      os: "win32",
      arch: "x64",
      avx2: false,
    },
  ]

const targets = singleFlag
  ? allTargets.filter((item) => {
    if (item.os !== process.platform || item.arch !== process.arch) {
      return false
    }

    // When building for the current platform, prefer a single native binary by default.
    // Baseline binaries require additional Bun artifacts and can be flaky to download.
    if (item.avx2 === false) {
      return baselineFlag
    }

    // also skip abi-specific builds for the same reason
    if (item.abi !== undefined) {
      return false
    }

    return true
  })
  : allTargets

await $`rm -rf dist`
await $`mkdir -p dist`

// Build frontend for release bundling — skip if source unchanged
const frontendHashFile = path.join(dir, "packages/app/dist/.build-hash")
const computeFrontendHash = async () => {
  // Hash all source files + package.json to detect changes
  const result = await $`find packages/app/src packages/ui/src -type f -print0 | sort -z | xargs -0 sha256sum | sha256sum`.text()
  const pkgHash = await $`sha256sum packages/app/package.json packages/ui/package.json`.text()
  const hasher = new Bun.CryptoHasher("sha256")
  hasher.update(result)
  hasher.update(pkgHash)
  return hasher.digest("hex")
}

const currentFrontendHash = await computeFrontendHash()
let frontendSkipped = false

if (fs.existsSync(frontendHashFile)) {
  const previousHash = fs.readFileSync(frontendHashFile, "utf-8").trim()
  if (previousHash === currentFrontendHash) {
    console.log("frontend up-to-date, skipping build")
    frontendSkipped = true
  }
}

if (!frontendSkipped) {
  console.log("building frontend")
  await $`bun run --cwd packages/app build`
  fs.writeFileSync(frontendHashFile, currentFrontendHash)
}
await $`tar -czf dist/opencode-frontend.tar.gz -C packages/app/dist .`

const binaries: Record<string, string> = {}
if (!skipInstall) {
  await $`bun install --os="*" --cpu="*" @opentui/core@${pkg.dependencies["@opentui/core"]}`
  await $`bun install --os="*" --cpu="*" @parcel/watcher@${pkg.dependencies["@parcel/watcher"]}`
}
for (const item of targets) {
  const name = [
    pkg.name,
    // changing to win32 flags npm for some reason
    item.os === "win32" ? "windows" : item.os,
    item.arch,
    item.avx2 === false ? "baseline" : undefined,
    item.abi === undefined ? undefined : item.abi,
  ]
    .filter(Boolean)
    .join("-")
  console.log(`building ${name}`)
  await $`mkdir -p dist/${name}/bin`
  await $`cp ./webctl.sh dist/${name}/bin/webctl.sh`

  const parserWorker = fs.realpathSync(path.resolve(dir, "./node_modules/@opentui/core/parser.worker.js"))

  // Use platform-specific bunfs root path based on target OS
  const bunfsRoot = item.os === "win32" ? "B:/~BUN/root/" : "/$bunfs/root/"
  const workerRelativePath = path.relative(dir, parserWorker).replaceAll("\\", "/")

  await Bun.build({
    conditions: ["browser"],
    tsconfig: "./tsconfig.json",
    plugins: [solidPlugin],
    sourcemap: "external",
    compile: {
      autoloadBunfig: false,
      autoloadDotenv: false,
      //@ts-ignore (bun types aren't up to date)
      autoloadTsconfig: true,
      autoloadPackageJson: true,
      target: name.replace(pkg.name, "bun") as any,
      outfile: `dist/${name}/bin/opencode`,
      execArgv: [`--user-agent=opencode/${Script.version}`, "--use-system-ca", "--"],
      windows: {},
    },
    entrypoints: ["./packages/opencode/src/index.ts", parserWorker],
    define: {
      OPENCODE_VERSION: `'${Script.version}'`,
      OTUI_TREE_SITTER_WORKER_PATH: bunfsRoot + workerRelativePath,
      OPENCODE_CHANNEL: `'${Script.channel}'`,
      OPENCODE_LIBC: item.os === "linux" ? `'${item.abi ?? "glibc"}'` : "",
    },
  })

  // Build internal MCP servers
  const mcpPackages = ["system-manager", "refacting-merger", "gcp-grounding"]
  for (const mcpPkg of mcpPackages) {
    const mcpSrc = `./packages/mcp/${mcpPkg}/src/index.ts`
    if (!fs.existsSync(mcpSrc)) continue

    console.log(`building MCP: ${mcpPkg} for ${name}`)
    await $`mkdir -p dist/${name}/mcp`
    await Bun.build({
      tsconfig: "./tsconfig.json",
      compile: {
        autoloadBunfig: false,
        autoloadDotenv: false,
        autoloadTsconfig: true,
        autoloadPackageJson: true,
        target: name.replace(pkg.name, "bun") as any,
        outfile: `dist/${name}/mcp/${mcpPkg}`,
        execArgv: [`--user-agent=opencode-mcp-${mcpPkg}/${Script.version}`, "--use-system-ca", "--"],
      },
      entrypoints: [mcpSrc],
      define: {
        OPENCODE_VERSION: `'${Script.version}'`,
      },
    })
  }

  await $`rm -rf ./dist/${name}/bin/tui`
  await Bun.file(`dist/${name}/package.json`).write(
    JSON.stringify(
      {
        name,
        version: Script.version,
        os: [item.os],
        cpu: [item.arch],
      },
      null,
      2,
    ),
  )
  binaries[name] = Script.version
}

if (Script.release) {
  for (const key of Object.keys(binaries)) {
    if (key.includes("linux")) {
      await $`tar -czf ../../${key}.tar.gz *`.cwd(`dist/${key}/bin`)
    } else {
      await $`zip -r ../../${key}.zip *`.cwd(`dist/${key}/bin`)
    }
  }
  await $`gh release upload v${Script.version} ./dist/*.zip ./dist/*.tar.gz --clobber`
}

export { binaries }
