#!/usr/bin/env bun

import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

if (process.argv.includes("--help") || process.argv.includes("-h")) {
  console.log(`Usage: bun run models:update-snapshot

Fetch latest models metadata and regenerate:
  packages/opencode/src/provider/models-snapshot.ts

Environment variables:
  OPENCODE_MODELS_URL   Override source base URL (default: https://models.dev)
  MODELS_DEV_API_JSON   Use local JSON file instead of network fetch
`)
  process.exit(0)
}

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`).then((x) => x.text())

await Bun.write(
  path.join(dir, "packages/opencode/src/provider/models-snapshot.ts"),
  `// Auto-generated by update-models-snapshot.ts - do not edit\nexport const snapshot = ${modelsData} as const\n`,
)

console.log("Updated packages/opencode/src/provider/models-snapshot.ts")
